### ISSUE TITLE
New update adds lots of broken commands/break prev. working ones.

### ISSUE THREAD

**Issue by ad2017gd** [Caty-the-AI/ColdConsole#5]
I have tested some commands and most just dont work:

CUN
execscript
read
ls
man (it DOES work but it crashes if you dont give any arguments)
del
update (server is offline)

I am going to add more commands if i find other stuff.
Please test your shit before making an update.

**Comment by Caty-the-AI** [comment]
So this is right but wrong at the same time. We added a args system and I can confirm they are working.
I forgot to test it and to add an try/catch so it won't crash. I hope you have a nice day, we will be fixing it.
Bye!
